ALTER TABLE general
  ADD COLUMN
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL;

ALTER TABLE events
  ADD COLUMN
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL;

ALTER TABLE general_items
  ADD COLUMN
    list_id INTEGER REFERENCES general(id) ON DELETE CASCADE NOT NULL;

ALTER TABLE event_items
  ADD COLUMN
    list_id INTEGER REFERENCES events(id) ON DELETE CASCADE NOT NULL;